pull_request_rules:
  - name: automatic merge for master when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge