FROM tensorflow/tensorflow:devel-gpu-py3
COPY sources.list.ubuntu18.04 /etc/apt/sources.list

# install tools 
COPY install.sh /install.sh
RUN /bin/bash /install.sh

#add user
ENV ROLE deltann
RUN adduser --disabled-password --gecos '' --shell '/bin/bash' $ROLE   && adduser $ROLE sudo   && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER $ROLE 

CMD ["/bin/bash", "-c"]
