FROM tensorflow/tensorflow:2.0.0-gpu-py3
COPY sources.list.ubuntu18.04 /etc/apt/sources.list

# install tools 
COPY install.sh /install.sh
RUN /bin/bash /install.sh

# install gcc
COPY install_user.sh /ci/install_user.sh
RUN /bin/bash /ci/install_user.sh

RUN sudo mkdir workspace && sudo chown delta: /workspace
RUN cd /workspace && git clone --depth 1 https://github.com/didi/delta.git
RUN cd /workspace/delta/tools && make basic
WORKDIR /workspace/delta

CMD ["/bin/bash", "-c"]
